version: '3'
services:
    twitter-countdown:
        restart: always
        container_name: twitter-countdown
        build: .
        volumes:
          - "./:/app"
        env_file:
          - .env